### ISSUE TITLE
full patch C code of BugFixNoDup

### ISSUE THREAD

**Issue by shy1224** [SteveKommrusch/VRepair#17]
Does the patch section of data for BugFixNoDup have the full patch C code, or is there a script to restore the full patch code?

**Comment by chenzimin** [comment]
VRepair is a continuation over "Using Sequence-to-Sequence Learning for Repairing C Vulnerabilities", therefore we use the same dataset. It is located at https://zenodo.org/records/4067881

**Comment by monperrus** [comment]
FTR, per the README, the files are also at https://github.com/ASSERT-KTH/VRepair/releases/download/v20240223/BugFix.tar.bz2
